spring:
  application:
    name: spring-admin-service

  datasource:
    url: jdbc:mysql://localhost:3307/multi
    username: root
    password: multi
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true


server:
  port: 8084
