version: '3.8'
services:
  mysql8:
    image: mysql:8.0
    container_name: mysql8-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: msa_project
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3307:3307"
    volumes:
      - mysql8-data:/var/lib/mysql
volumes:
  mysql8-data:
