spring:
  application:
    name: spring-user-service

  datasource:
    url: jdbc:mysql://localhost:3307/multi
    username: root
    password: multi
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true

  cloud:
    compatibility-verifier:
      enabled: false

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
