spring:
  application:
    name: spring-gateway-service

  cloud:
    gateway:
      routes:
        # /users/** -> spring-user-service로 라우팅
        - id: user-service
          uri: http://localhost:8083
          predicates:
            - Path=/users/**

        # /admin/** -> spring-admin-service로 라우팅
        - id: admin-service
          uri: http://localhost:8084
          predicates:
            - Path=/admin/**

      # 기본 필터 설정 (선택 사항)
      default-filters:
        - AddRequestHeader=Gateway-Request, GatewayRequestHeaderValue

server:
  port: 8081
