spring:
  application:
    name: spring-gateway-service

  cloud:
    gateway:
      routes:
        # 라우트 ID는 각 서비스에 대해 고유해야 함
        - id: user-service-route # spring-user-service
          uri: http://localhost:8083
          predicates:
            - Path=/users/**

        - id: admin-service-route # spring-admin-service
          uri: http://localhost:8084
          predicates:
            - Path=/admin/**

      # 기본 필터 (선택 사항)
      default-filters:
        - AddRequestHeader=Gateway-Request, GatewayRequestHeaderValue

server:
  port: 8081
