spring:
  application:
    name: spring-core-service

  datasource:
    url: jdbc:mysql://localhost:3307/multi
    username: root
    password: multi
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 개발 환경에서는 'update', 운영 환경에서는 'validate' 사용 권장
    show-sql: true
    properties:
      hibernate.format_sql: true

  cloud:
    compatibility-verifier:
      enabled: false

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
